In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
df=pd.read_csv("Gold.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 676 entries, 0 to 675
Data columns (total 21 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Date                                    676 non-null    object
 1   Price 2 Days Prior                      676 non-null    float64
 2   Price 1 Day Prior                       676 non-null    float64
 3   Price Today                             676 non-null    float64
 4   Price Tomorrow                          675 non-null    float64
 5   Price Change Tomorrow                   675 non-null    float64
 6   Price Change Ten                        666 non-null    float64
 7   Std Dev 10                              667 non-null    float64
 8   Twenty Moving Average                   676 non-null    float64
 9   Fifty Day Moving Average                676 non-null    float64
 10  200 Day Moving Average                  676 non-null    float64
 11  Monthly Inflation Rate                  676 non-null    float64
 12  EFFR Rate                               676 non-null    float64
 13  Volume                                  676 non-null    int64
 14  Treasury Par Yield Month                676 non-null    float64
 15  Treasury Par Yield Two Year             676 non-null    float64
 16  Treasury Par Yield Curve Rates (10 Yr)  676 non-null    float64
 17  DXY                                     676 non-null    float64
 18  SP Open                                 676 non-null    float64
 19  VIX                                     676 non-null    float64
 20  Crude                                   676 non-null    float64
dtypes: float64(19), int64(1), object(1)
memory usage: 111.0+ KB

In [4]:
df.describe

<bound method NDFrame.describe of        Date  Price 2 Days Prior  Price 1 Day Prior  Price Today  \
0    8/7/24             2405.87            2384.90      2385.83
1    8/6/24             2442.74            2405.87      2384.90
2    8/5/24             2447.17            2442.74      2405.87
3    8/2/24             2447.23            2447.17      2442.74
4    8/1/24             2411.09            2447.23      2447.17
..      ...                 ...                ...          ...
671  1/7/22             1810.28            1791.61      1796.41
672  1/6/22             1813.88            1810.28      1791.61
673  1/5/22             1804.27            1813.88      1810.28
674  1/4/22             1815.73            1804.27      1813.88
675  1/3/22             1804.64            1829.05      1804.27

     Price Tomorrow  Price Change Tomorrow  Price Change Ten  Std Dev 10  \
0               NaN                    NaN               NaN   30.155078
1           2385.83                   0.93               NaN   29.423936
2           2384.90                 -20.97               NaN   28.341301
3           2405.87                 -36.87               NaN   28.616661
4           2442.74                  -4.43               NaN   26.084796
..              ...                    ...               ...         ...
671         1801.52                   5.11             38.17         NaN
672         1796.41                   4.80             47.40         NaN
673         1791.61                 -18.67             28.30         NaN
674         1810.28                  -3.60              0.45         NaN
675         1813.88                   9.61             14.95         NaN

     Twenty Moving Average  Fifty Day Moving Average  ...  \
0                2414.7450                 2368.2948  ...
1                2414.1525                 2367.7916  ...
2                2413.2305                 2367.1584  ...
3                2411.0920                 2365.7250  ...
4                2408.5670                 2363.5624  ...
..                     ...                       ...  ...
671               450.8225                  180.3290  ...
672               361.0020                  144.4008  ...
673               271.4215                  108.5686  ...
674               180.9075                   72.3630  ...
675                90.2135                   36.0854  ...

     Monthly Inflation Rate  EFFR Rate  Volume   Treasury Par Yield Month  \
0                       3.0       5.33       96                      5.50
1                       3.0       5.33       89                      5.50
2                       3.0       5.33       86                      5.52
3                       3.0       5.33       89                      5.54
4                       3.0       5.33       83                      5.55
..                      ...        ...      ...                       ...
671                     7.5       0.10       71                      0.05
672                     7.5       0.10       73                      0.04
673                     7.5       0.10       74                      0.05
674                     7.5       0.10       74                      0.06
675                     7.5       0.10       74                      0.05

     Treasury Par Yield Two Year  Treasury Par Yield Curve Rates (10 Yr)  \
0                           4.00                                    3.96
1                           3.99                                    3.90
2                           3.89                                    3.78
3                           3.88                                    3.80
4                           4.16                                    3.99
..                           ...                                     ...
671                         0.87                                    1.76
672                         0.88                                    1.73
673                         0.83                                    1.71
674                         0.77                                    1.66
675                         0.78                                    1.63

        DXY  SP Open    VIX  Crude
0    103.37  5293.13  24.77  72.84
1    102.78  5206.42  33.71  73.86
2    103.22  5151.14  23.39  74.21
3    104.31  5376.63  20.52  76.87
4    104.07  5537.84  16.20  78.59
..      ...      ...    ...    ...
671   96.26  4697.66  19.85  79.62
672   96.20  4693.39  20.29  77.24
673   96.31  4787.99  17.07  77.18
674   96.19  4804.51  16.57  76.02
675   95.67  4778.14  17.60  75.69

[676 rows x 21 columns]>

In [5]:
df.columns

Index(['Date', 'Price 2 Days Prior', 'Price 1 Day Prior', 'Price Today',
       'Price Tomorrow', 'Price Change Tomorrow', 'Price Change Ten',
       'Std Dev 10', 'Twenty Moving Average', 'Fifty Day Moving Average',
       '200 Day Moving Average', 'Monthly Inflation Rate', 'EFFR Rate',
       'Volume ', 'Treasury Par Yield Month', 'Treasury Par Yield Two Year',
       'Treasury Par Yield Curve Rates (10 Yr)', 'DXY', 'SP Open', 'VIX',
       'Crude'],
      dtype='object')

In [6]:
df.head()

,Date,Price 2 Days Prior,Price 1 Day Prior,Price Today,Price Tomorrow,Price Change Tomorrow,Price Change Ten,Std Dev 10,Twenty Moving Average,Fifty Day Moving Average,...,Monthly Inflation Rate,EFFR Rate,Volume,Treasury Par Yield Month,Treasury Par Yield Two Year,Treasury Par Yield Curve Rates (10 Yr),DXY,SP Open,VIX,Crude
0,8/7/24,2405.87,2384.90,2385.83,NaN,NaN,NaN,30.155078,2414.7450,2368.2948,...,3.0,5.33,96,5.50,4.00,3.96,103.37,5293.13,24.77,72.84
1,8/6/24,2442.74,2405.87,2384.90,2385.83,0.93,NaN,29.423936,2414.1525,2367.7916,...,3.0,5.33,89,5.50,3.99,3.90,102.78,5206.42,33.71,73.86
2,8/5/24,2447.17,2442.74,2405.87,2384.90,-20.97,NaN,28.341301,2413.2305,2367.1584,...,3.0,5.33,86,5.52,3.89,3.78,103.22,5151.14,23.39,74.21
3,8/2/24,2447.23,2447.17,2442.74,2405.87,-36.87,NaN,28.616661,2411.0920,2365.7250,...,3.0,5.33,89,5.54,3.88,3.80,104.31,5376.63,20.52,76.87
4,8/1/24,2411.09,2447.23,2447.17,2442.74,-4.43,NaN,26.084796,2408.5670,2363.5624,...,3.0,5.33,83,5.55,4.16,3.99,104.07,5537.84,16.20,78.59